### ISSUE TITLE
MFXVideoCORE_SyncOperation error -7

### ISSUE THREAD

**Issue by Brenda1124WYQ** [intel/libvpl#128] opened 2024-03-08 02:30 UTC
用dxgi抓屏+vpl编码之后，大概半个小时到1个小时以内会出现MFXVideoCORE_SyncOperation 操作失败，报-7错误码

**Comment by ma3uk** [comment] 2024-03-08 16:11
Try a workaround for using texture import using GetRefCount, at least this method works for me - https://github.com/ma3uk/obs-qsv-onevpl/blob/28fb5d534eac836db93b530bfe9d63056fd71ab0/obs-qsvonevpl/obs-qsv-onevpl-encoder-internal.cpp#L1644

**Comment by ma3uk** [comment] 2024-03-08 16:24
I'm facing the same problem, and the solution above is the only working option at the moment.
https://github.com/oneapi-src/oneVPL-intel-gpu/issues/318

**Comment by mav-intel** [comment] 2024-03-12 15:53
Duplicate of https://github.com/oneapi-src/oneVPL-intel-gpu/issues/318. Please follow the issue there

**Closed by mav-intel** 2024-03-12 15:53 UTC
